apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-app-touch-deployment-dev
  namespace: group-4
  labels:
    app: simple-node-app-touch-deployment-dev
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 50%
  selector:
    matchLabels:
      app: simple-node-app-touch-deployment-dev
  template:
    metadata:
      labels:
        app: simple-node-app-touch-deployment-dev
    spec:
      containers:
        - name: simple-node-app-touch-dev
          image: touchsung/simple-node-app:d35664671d5560091a7a8d54255a1e4af29e0e20
          ports:
            - containerPort: 3000
