name: Deploy to Prod

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/simple-node-app

jobs:
  deploy_to_k8s:
    name: Deploy to K8S
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Retag Image and Push
        run: |
          export NEW_TAG=${GITHUB_REF#refs/tags/}
          export NEW_IMAGE=${{ env.IMAGE_NAME }}:$NEW_TAG
          docker pull ${{ env.IMAGE_NAME }}:dev
          docker tag ${{ env.IMAGE_NAME }}:dev $NEW_IMAGE
          docker push $NEW_IMAGE
      - name: Connect K8S Cluster
        run: ${{ secrets.KUBE_CONFIG }}
      - name: Modify Manifest and Update YAML File
        run: |
          export NAME_WITH_TAG=${{ env.IMAGE_NAME }}:${GITHUB_REF#refs/tags/}
          yq -i '.spec.template.spec.containers[0].image=strenv(NAME_WITH_TAG)' ./manifest/prod/deployment.yaml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout main
          git add ./manifest/prod/deployment.yaml
          git commit -m "release image to ${NAME_WITH_TAG}"
          git push origin main
      - name: Deploy to Cluster
        run: kubectl apply -f ./manifest/prod/.
